# Generated by Django 3.1.7 on 2021-02-20 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriaTovara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название категории товара')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категория товаров',
            },
        ),
        migrations.CreateModel(
            name='KategoriaUslug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название категории услуг')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категория услуг',
            },
        ),
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('na_glavnuy', models.BooleanField(default=False, verbose_name='Выводить на главной')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('opisanie', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('kategoria_uslug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategoriatovara', verbose_name='Категория услуг')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название товара')),
                ('na_glavnuy', models.BooleanField(default=False, verbose_name='Выводить на главной')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('opisanie', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('kategoria_tovara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategoriatovara', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
