# Generated by Django 3.1.7 on 2021-02-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210220_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
