# Generated by Django 3.1.7 on 2021-03-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210306_2135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
